
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";
import ReduxProvider from "@/components/ReduxProvider";
import { ThemeProvider } from "@/components/theme-provider"
import Navbar from "@/components/Navbar/Navbar";


export const metadata = {
  title: "BitLinks",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <ReduxProvider>
            <Toaster />
            <Navbar />
            {children}

          </ReduxProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
